name: Update

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade requests rfeed
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rss files
          path: rss/*.rss
